[project]
name = "langchain-agent-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "grandalf>=0.8",
    "langchain[ollama]>=1.2.10",
    "requests>=2.32.5",
    "rich>=14.3.2",
]
